export const formDefaultValues = {
  oneWayTrip: true,
  roundWay: false,
  origin: "",
  destination: "",
  journeyDate: "",
  returnDate: "",
  number_of_adults: 1,
  number_of_children: 0,
  number_of_infants: 0,
  adults: [],
  children: [],
  infants: [],

  airline: "",
  cabin: "",
  basicFare: "",
  taxes: "",
  sc: "",
  discount: "",
  totalAmount: "",

  gender: "",
  firstName: "",
  surName: "",
  date_of_birth: "",
  email: "",
  phone: "",
  
  pnr: "",
  ticket: "",
  issueBy: "",
  ledger: "",
  code: "",
};
